FROM ubuntu:20.04

# Setup user 
RUN useradd -ms /bin/bash sandbox

# Setup the working directory
WORKDIR /home/sandbox

# update the ubunut system 
RUN apt update && apt upgrade -y

# Install nano and curl
RUN apt install nano curl -y 

# Install Nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get

# Configuring terminal to display the current working directory
RUN echo "PS1='\w '" >> /home/sandbox/.bashrc

# Setup final working directory
WORKDIR /home/sandbox/app 